name: Padavan-Mahtab

on:
  workflow_dispatch:
    inputs:
      production:
        description: Set the firmware model：
        default: "A3004NS"
        required: false
      cloneurl:
        description: Set the source address：
        default: "https://github.com/W5x/Padavan-mahtab.git"
        #default: "https://gitlab.com/mahtabctg/padavan-ng.git"
        # default: "https://github.com/MeIsReallyBa/padavan-4.4.git"
        # default: "https://github.com/keke1023/Padavan.git"
        # default: "https://github.com/vb1980/Padavan-KVR.git"
        required: false

env:
  IMAGES: /opt/images
  RT_N56U: /opt/rt-n56u
  TRUNK: /opt/rt-n56u/trunk
  TZ: Asia/Shanghai
  DIY_P1_SH: diy-part1.sh

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin > /dev/null
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p $RT_N56U
          mkdir -p $IMAGES
          sudo chown $USER:$GROUPS $RT_N56U

      - name: Clone source code and build toolchain
        run: |
          echo "DATE=$(TZ='Asia/Shanghai' date '+%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          echo "NAME=Padavan-${{ github.event.inputs.production }}" >> $GITHUB_ENV
          echo start compile time： >> $IMAGES/readme.txt
          TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S' >> $IMAGES/readme.txt
          git clone --depth=1 ${{ github.event.inputs.cloneurl }} $RT_N56U > /dev/null
          cd $RT_N56U/toolchain
          sh dl_toolchain.sh > /dev/null

      - name: Load custom diy setting
        run: |
          cp -f ./$DIY_P1_SH $TRUNK/$DIY_P1_SH
          chmod +x $TRUNK/$DIY_P1_SH
          pushd $TRUNK
          sh ./$DIY_P1_SH
          popd

      - name: Compile the firmware
        run: |
          for m in ${{ github.event.inputs.production }}; do
            pushd $TRUNK
            echo "::group::start compiling ${m}..."
            sudo ./clear_tree || echo
            sudo ./build_firmware_modify $m > /dev/null
            ls -l images
            sudo mv -f images/*.trx $IMAGES
            echo "::endgroup::"
            popd
          done

      - name: Organize compile infomations
        run: |
          cd $IMAGES
          echo complete compile time： >> readme.txt
          TZ='Asia/Shanghai'  date  '+%Y-%m-%d %H:%M:%S' >> readme.txt
          echo >> readme.txt
          echo source information： >> readme.txt
          pushd $RT_N56U
          git ls-remote --get-url origin >> $IMAGES/readme.txt
          git log --shortstat >> $IMAGES/readme.txt
          popd
          echo >> readme.txt
          echo "md5 Check value：" >> readme.txt
          for m in *.trx
          do
            mv -fv "$m" "${m%.*}_${{ env.DATE }}.trx"
          done
          md5sum *.trx >> readme.txt || echo
          ls -lh

      - name: Upload images directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.NAME }}
          path: ${{ env.IMAGES }}
